kind: ConfigMap
apiVersion: v1
metadata:
  name: bulkie-cm
  namespace: bulkie
  labels:
    app: bulkie
    service: bulkie
data:
  ConnectionString: host=postgres-postgresql.bulkie.svc.cluster.local;database=bulkie;user id=postgres;password=T9zA8GZthL 
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  CheckUpdateTime: "30000"
  PORT: "80"
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: bulkie
  namespace: bulkie
  labels:
    app: bulkie
    service: bulkie
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bulkie
  template:
    metadata:
      labels:
        app: bulkie
        service: bulkie
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "bulkie-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: bulkie-api
          image: bulkie/bulkie-api:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bulkie-cm

---

apiVersion: v1
kind: Service
metadata:
  name: bulkie-api
  namespace: bulkie
  labels:
    app: bulkie
    service: bulkie
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    service: bulkie
