// <auto-generated />
using System;
using Bulkie.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bulkie.API.Migrations
{
    [DbContext(typeof(BulkieContext))]
    [Migration("20210813211238_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bulkie.API.Model.Bulkie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Completed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bulkies");

                    b.ToTable("bulkies");
                });

            modelBuilder.Entity("Bulkie.API.Model.BulkieFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BulkieId")
                        .HasColumnType("uuid")
                        .HasColumnName("bulkieid");

                    b.Property<DateTime>("Completed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("FileReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("filereferenceid");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bulkiefiles");

                    b.HasIndex("BulkieId")
                        .HasDatabaseName("ix_bulkiefiles_bulkieid");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bulkiefiles_status");

                    b.ToTable("bulkiefiles");
                });

            modelBuilder.Entity("Bulkie.API.Model.BulkieFile", b =>
                {
                    b.HasOne("Bulkie.API.Model.Bulkie", "Bulkie")
                        .WithMany("BulkieFiles")
                        .HasForeignKey("BulkieId")
                        .HasConstraintName("fk_bulkiefiles_bulkies_bulkieid");

                    b.Navigation("Bulkie");
                });

            modelBuilder.Entity("Bulkie.API.Model.Bulkie", b =>
                {
                    b.Navigation("BulkieFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
